# Generated by Django 3.2.15 on 2022-09-25 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HitManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='', max_length=100)),
                ('targeturl', models.TextField()),
                ('targetcount', models.IntegerField(default=1)),
                ('actualcount', models.IntegerField(default=1)),
                ('starttime', models.DateTimeField(auto_now=True)),
                ('endtime', models.DateTimeField(blank=True, default='0001-01-01 00:00:01', null=True)),
                ('debugstatus', models.BooleanField(default=False)),
                ('humanizestatus', models.BooleanField(default=False)),
                ('loggingstatus', models.BooleanField(default=True)),
                ('cleanupstatus', models.BooleanField(default=True)),
                ('forcedstop', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hits Management Table',
                'db_table': 'hitweb_manager',
            },
        ),
    ]
