# Generated by Django 3.2.15 on 2022-09-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxyip', models.CharField(default='', max_length=16)),
                ('proxyport', models.IntegerField(default=3128)),
                ('proxytype', models.CharField(default='https', max_length=10)),
                ('proxyurl', models.CharField(default='', max_length=35)),
                ('provider', models.CharField(default='rayobyte', max_length=20)),
                ('addedon', models.DateTimeField(auto_now=True)),
                ('removedon', models.DateTimeField(default='0001-01-01 00:00:01')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Proxies Management Table',
                'db_table': 'hitweb_proxies',
            },
        ),
        migrations.CreateModel(
            name='ProxyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hitapp.hitmanager')),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hitapp.proxies')),
            ],
            options={
                'verbose_name': 'Proxies Usage Table',
                'db_table': 'hitweb_proxyusage',
            },
        ),
    ]
