# Generated by Django 3.2.15 on 2022-09-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitapp', '0003_apikeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeys',
            name='deletedate',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
